-- ===========================================================================
-- Add a per-session summary for cross-session memory recall.
-- ===========================================================================
-- Each session gets a short, gentle summary (generated by the server's
-- /api/summarize endpoint) so that on a later visit Sova can recall what the
-- person talked about before — without replaying raw, potentially distressing
-- transcript text. Written by the owning user via the existing update policy;
-- no new RLS needed.
-- ===========================================================================

alter table public.sessions
  add column if not exists summary text;
